version: '3.4'

services:
  yaos.api.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002"
  yaos.api.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6003"

  yaos.api.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001"

  yaos.api.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6004"
